const actionTypes = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
  DISABLE_SWITCH_BTNS: 'DISABLE_SWITCH_BTNS',
  ENABLE_SWITCH_BTNS: 'ENABLE_SWITCH_BTNS'
};

export default actionTypes;